#!/usr/bin/env python3
"""Writes egg-ventacart.json from the pieces beside it.

The install script lives in install.sh so it can be read and diffed as a
script. This embeds it, so the file you import into the panel and the script
in the repository are always the same one.

    python3 egg/build-egg.py
"""

import json
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
IMAGE = "ghcr.io/pao2pao16/ventacart-yolk:php8.4"


def var(name, env, description, default="", rules="nullable|string", viewable=True, editable=False):
    return {
        "name": name,
        "description": description,
        "env_variable": env,
        "default_value": default,
        "user_viewable": viewable,
        "user_editable": editable,
        "rules": rules,
        "field_type": "text",
    }


VARIABLES = [
    var("Admin email", "ADMIN_EMAIL",
        "The first admin's email, applied once when the store is created. The admin signs in as admin, not with this email.",
        rules="required|email|max:191"),
    var("Admin password", "ADMIN_PASSWORD",
        "The first admin's password, applied once when the store is created.",
        rules="required|string|min:12|max:191", viewable=False),
    var("Site address", "APP_URL",
        "The address people open, with http:// or https://. The node address and port to begin with, the domain once one points here.",
        default="http://127.0.0.1", rules="required|url|max:191"),
    var("Database host", "DB_HOST",
        "The Endpoint host from this server's Databases tab, as the container reaches it. Not 127.0.0.1.",
        rules="nullable|string|max:191"),
    var("Database port", "DB_PORT", "The Endpoint port from the Databases tab.",
        default="3306", rules="required|integer|between:1,65535"),
    var("Database name", "DB_DATABASE", "From the Databases tab.", rules="nullable|string|max:191"),
    var("Database user", "DB_USERNAME", "From the Databases tab.", rules="nullable|string|max:191"),
    var("Database password", "DB_PASSWORD", "From the Databases tab.",
        rules="nullable|string|max:191", viewable=False),
    var("Database driver", "DB_CONNECTION", "Always mysql.",
        default="mysql", rules="required|string|in:mysql", viewable=False),
    var("Environment", "APP_ENV", "production for anyone else's eyes.",
        default="production", rules="required|string|in:production,staging,local", viewable=False),
    var("Debug pages", "APP_DEBUG", "Never true on a store other people can reach.",
        default="false", rules="required|string|in:true,false", viewable=False),
    var("Repository", "GIT_REPO", "VentaCart's GitHub repository, owner/name.",
        default="pao2pao16/venta", rules="required|string|regex:/^[\\w.-]+\\/[\\w.-]+$/", viewable=False),
    var("Branch", "GIT_BRANCH", "The branch installed, and followed when updates are on.",
        default="main", rules="required|string|max:100", viewable=False),
    var("GitHub token", "GIT_TOKEN",
        "A fine-grained token with read-only Contents access to the repository. Needed while the repository is private. Never shown to server users.",
        rules="nullable|string|max:255", viewable=False),
    var("Update on start", "AUTO_UPDATE",
        "1 pulls the latest of the branch on every start. 0 keeps the installed code.",
        default="0", rules="required|boolean", viewable=False),
    var("Migrate on start", "AUTO_MIGRATE",
        "1 runs new migrations on every start. 0 only reports them, so a running store is never changed without someone reading the release notes first. A new store is always set up either way.",
        default="0", rules="required|boolean", viewable=False),
    var("PHP workers", "FPM_WORKERS",
        "How many requests PHP serves at once. About one per 100 MB of the server's memory.",
        default="6", rules="required|integer|between:4,64", viewable=False),
]


def main():
    egg = {
        "_comment": "Generated by egg/build-egg.py in pao2pao16/ventacart-pterodactyl. Edit install.sh or build-egg.py, not this file.",
        "meta": {"version": "PTDL_v2", "update_url": None},
        "exported_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S+00:00"),
        "name": "VentaCart",
        "author": "pao2pao16@gmail.com",
        "description": "A VentaCart store: nginx, PHP, the queue worker and the scheduler in one server. The console runs artisan commands.",
        "features": None,
        "docker_images": {"PHP 8.4": IMAGE},
        "file_denylist": [],
        "startup": "ventacart-boot",
        "config": {
            "files": "{}",
            "startup": json.dumps({"done": "VentaCart is ready"}),
            "logs": "{}",
            "stop": "stop",
        },
        "scripts": {
            "installation": {
                "script": (HERE / "install.sh").read_text(encoding="utf-8").replace("\r\n", "\n"),
                "container": IMAGE,
                "entrypoint": "bash",
            }
        },
        "variables": VARIABLES,
    }
    out = HERE / "egg-ventacart.json"
    out.write_text(json.dumps(egg, indent=4) + "\n", encoding="utf-8")
    print(f"wrote {out.relative_to(HERE.parent)}")


if __name__ == "__main__":
    main()
